vim.cmd('set expandtab')
vim.cmd('set tabstop=2')
vim.cmd('set softtabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set clipboard=unnamedplus')
vim.cmd('set cursorline')
vim.cmd('set termguicolors')
vim.cmd('set undofile')
vim.cmd('set undolevels=1000')
vim.cmd('set confirm')
vim.cmd('set conceallevel=2')
vim.cmd('set completeopt')
vim.cmd('set shiftround')
vim.cmd('set smartcase')
vim.g.mapleader = " "

